Fixed clang-format scripts

diff --git a/githooks/pre-commit b/githooks/pre-commit
--- a/githooks/pre-commit
+++ b/githooks/pre-commit
@@ -6,6 +6,14 @@
 
 set -eu
 
+readonly CLANG_FORMAT="$(which clang-format)"
+
+if [[ ! -x "$CLANG_FORMAT" ]]; then
+	printf "clang-format is not found:\n"
+	printf "\t$ sudo apt-get install clang-format\n"
+	exit 1
+fi
+
 readonly DELETE_OLD_PATCHES=false
 
 # file extensions to parse
@@ -57,14 +65,6 @@ if git rev-parse --verify HEAD >/dev/null 2>&1; then
 else
 	# initial commit: diff against an empty tree object
 	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
-fi
-
-readonly CLANG_FORMAT="$(which clang-format)"
-
-if [[ ! -x "$CLANG_FORMAT" ]]; then
-	printf "$CLANG_FORMAT is not found:\n"
-	printf "\t$ sudo apt-get install $CLANG_FORMAT\n"
-	exit 1
 fi
 
 # create a random filename to store our generated patch
